--- 
#Apache deploy to new webservers
- hosts: webservers_2
  become: 'yes'
  roles:
    - apache
    
#HAproxy tasks in Loadbalancer
- hosts: loadbalancer
  become: 'yes'
  roles:
    - haproxy

#Siege tasks in Siege host
- hosts: siege
  become: 'yes'
  roles:
    - siege
